version: '3'

services:
  api:
    container_name: api
    build: '.'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - database
    networks:
      - api-db
    ports:
      - '3333:3333'
      - '9229:9229'
    links: 
      - database


  database:
    container_name: database
    image: postgres:12
    environment: 
      - POSTGRES_DB=api
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks: 
      - api-db

volumes:
  database-data: 

networks:
      api-db:
          driver: bridge